<?php

namespace App\Http\Requests\Api\V1\Order;

use App\Enums\Order\AvailabilityStatus;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Validator;

class SubmitSupplierOrderResponseRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user() !== null;
    }

    /**
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'items' => [
                'required',
                'array',
                'min:1',
                'max:50',
            ],

            'items.*' => [
                'required',
                'array',
            ],

            'items.*.order_recipient_item_id' => [
                'required',
                'uuid',
                'distinct',
            ],

            'items.*.availability_status' => [
                'required',
                Rule::enum(AvailabilityStatus::class),
            ],

            'items.*.available_quantity' => [
                'required',
                'integer',
                'min:0',
            ],

            'items.*.offered_unit_price' => [
                'nullable',
                'numeric',
                'decimal:0,2',
                'min:0',
                'lt:10000000000000000',
            ],

            'items.*.response_notes' => [
                'nullable',
                'string',
                'max:2000',
            ],
        ];
    }

    /**
     * Validate headers and fields that must never become part of the public
     * request contract generated by Scramble.
     *
     * @return array<int, callable>
     */
    public function after(): array
    {
        return [
            function (Validator $validator): void {
                $idempotencyKey = trim(
                    (string) $this->header('Idempotency-Key', ''),
                );

                if ($idempotencyKey === '') {
                    $validator->errors()->add(
                        'Idempotency-Key',
                        'The Idempotency-Key header is required.',
                    );

                    return;
                }

                if (! Str::isUuid($idempotencyKey)) {
                    $validator->errors()->add(
                        'Idempotency-Key',
                        'The Idempotency-Key header must be a valid UUID.',
                    );
                }
            },

            function (Validator $validator): void {
                $items = $this->input('items', []);

                if (! is_array($items)) {
                    return;
                }

                foreach ($items as $index => $item) {
                    /*
                     * requested_quantity belongs to the authoritative OrderItem
                     * snapshot. A supplier must never override it from the client.
                     */
                    if (
                        is_array($item)
                        && array_key_exists('requested_quantity', $item)
                    ) {
                        $validator->errors()->add(
                            "items.$index.requested_quantity",
                            'The requested quantity field is prohibited.',
                        );
                    }
                }
            },
        ];
    }

    public function idempotencyKey(): string
    {
        return trim((string) $this->header('Idempotency-Key'));
    }

    /**
     * @return array{items: array<int, array<string, mixed>>}
     */
    public function responsePayload(): array
    {
        return $this->validated();
    }

    protected function prepareForValidation(): void
    {
        $items = $this->input('items');

        if (is_array($items)) {
            $items = array_map(
                static function ($item) {
                    if (! is_array($item)) {
                        return $item;
                    }

                    if (
                        array_key_exists('response_notes', $item)
                        && is_string($item['response_notes'])
                    ) {
                        $item['response_notes'] = trim(
                            $item['response_notes'],
                        );
                    }

                    return $item;
                },
                $items,
            );
        }

        $this->merge([
            'items' => $items,
        ]);
    }
}
